Flatten closed_results before assignment
I originally discovered the issue because of the following error messages in one of our tests:

```
undefined method `conform?' for [(ValidationResult
        (value "Undefiniert")
        (focus <http://example.com/base/rr_20221107093933331>)
        (path <https://www.ica.org/standards/RiC/ontology#type>)
        (shape shacl:RicoRecordResourceWithCategoryShape)
        (resultSeverity shacl:Violation)
        (component shacl:ClosedConstraintComponent)
        (message "closed node has extra property"))
       ]:Array

               next unless results.all?(&:conform?)
                                  ^^^^^
     # /Users/apf/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/shacl-0.4.0/lib/shacl/algebra/or.rb:34:in `all?'
```

I wondered where this array was coming from and did some deep-dives using the debugger. Since both `builtin_results` and `op_results` get flattend, I assume it should be the same for `closed_results`.